modLoader="javafml"
loaderVersion="[28.1,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/seafaring"

[[mods]]
modId="sea"
version="0.1.47"
displayName="Seafaring"
updateJSONURL="https://mc.deltawolf.tk/assets/endpoints/sea/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/seafaring"
logoFile="logo.png"
credits="Delta (XDeltaA77)"
authors="Delta (XDeltaA77)"
description='''
Go explore the ocean and find life a little different under the waves.
'''
#Require Forge
[[dependencies.sea]]
    modId="forge"
    mandatory=true
    versionRange="[28.1,)"
    ordering="NONE"
    side="BOTH"

#Require MC
[[dependencies.sea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
