modLoader="javafml"
loaderVersion="[28.1,)"
issueTrackerURL="https://github.com/XDelta/"

[[mods]]
modId="sea"
version="${file.jarVersion}"
displayName="Seafaring"
updateJSONURL="https://mc.deltawolf.tk/assets/endpoints/sea/update.json"
displayURL="https://mc.deltawolf.tk/"
logoFile="logo.png"
credits="Delta (XDeltaA77)"
authors="Delta (XDeltaA77)"
description='''
This is a placeholder description.
'''
#Require Forge
[[dependencies.sea]]
    modId="forge"
    mandatory=true
    versionRange="[28.1,)"
    ordering="NONE"
    side="BOTH"

#Require MC
[[dependencies.sea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
